---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    tables: false
    code_blocks: false
ratings:
  paths:
  - "**.js"
  - "**.md"
exclude_paths:
- test/
